import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './provider'
import { ShowNavBar } from './components'
import { Suspense } from 'react'
import LoadingC from './components/common/LoadingC'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body className={inter.className}>
        <Suspense fallback={<LoadingC />}>
          <Providers>
            <main className="dark text-foreground bg-background">
              <ShowNavBar />
              {children}
            </main>
          </Providers>
        </Suspense>
      </body>
    </html>
  )
}


